from __future__ import annotations

from fastapi import APIRouter

from app.models.contracts import BreathworkProtocol

router = APIRouter(prefix="/api/breathwork", tags=["breathwork"])


BREATHWORK_PROTOCOLS: list[BreathworkProtocol] = [
    BreathworkProtocol(
        id="nsdr",
        name="NSDR",
        category="Non-Sleep Deep Rest",
        tagline="Deep Reset For Nervous System Recovery",
        duration_mins=20,
        description="Non-Sleep Deep Rest is a guided down-regulation practice that combines stillness, body scanning, and deliberate breath pacing to shift the nervous system out of chronic stress. It is commonly used to improve recovery, mental clarity, and sleep pressure without actually falling asleep. Physiologically, it supports parasympathetic activity, can lower heart rate, and helps reduce excessive sympathetic arousal.",
        origin="Popularized in modern neuroscience circles as NSDR, drawing from yoga nidra and structured deep relaxation practices.",
        benefits=["Recovery", "Stress Relief", "Sleep Support"],
        effects={"hr": "decrease", "hrv": "increase", "temperature": None},
        difficulty="beginner",
        phases=[
            {"label": "Breathe In", "duration_sec": 4, "instruction": "Slow, quiet nasal inhale into the belly.", "animation": "expand"},
            {"label": "Hold", "duration_sec": 2, "instruction": "Pause softly without strain.", "animation": "hold"},
            {"label": "Breathe Out", "duration_sec": 6, "instruction": "Long, passive exhale and release the body.", "animation": "contract"},
        ],
        cycles=120,
    ),
    BreathworkProtocol(
        id="4-7-8",
        name="4-7-8 Breathing",
        category="Breathing Protocols",
        tagline="Rapid Calm Before Rest",
        duration_mins=10,
        description="The 4-7-8 method uses a measured inhale, extended hold, and slow exhale to quickly shift the body toward calm. It is often recommended before sleep or during high stress because the long exhalation increases vagal tone and the hold phase improves respiratory control. Over time, practitioners often notice improved emotional regulation and reduced reactivity.",
        origin="Derived from pranayama-inspired breath pacing and popularized in modern wellness by Dr. Andrew Weil.",
        benefits=["Calm", "Sleep", "Stress Relief"],
        effects={"hr": "decrease", "hrv": "increase", "temperature": None},
        difficulty="beginner",
        phases=[
            {"label": "Breathe In", "duration_sec": 4, "instruction": "Inhale through the nose for four counts.", "animation": "expand"},
            {"label": "Hold", "duration_sec": 7, "instruction": "Retain the breath gently for seven counts.", "animation": "hold"},
            {"label": "Breathe Out", "duration_sec": 8, "instruction": "Exhale slowly and completely for eight counts.", "animation": "contract"},
        ],
        cycles=10,
    ),
    BreathworkProtocol(
        id="buteyko-reduced-breathing",
        name="Buteyko Reduced Breathing",
        category="Breathing Protocols",
        tagline="Breathe Less, Improve Tolerance",
        duration_mins=12,
        description="Buteyko Reduced Breathing emphasizes lighter, quieter breaths to improve carbon dioxide tolerance and reduce chronic over-breathing. The technique aims to normalize respiratory chemistry, often helping people feel less air hunger over time while promoting a calmer baseline state. It is subtle, controlled, and intentionally conservative.",
        origin="Developed by Dr. Konstantin Buteyko in the Soviet Union for respiratory retraining.",
        benefits=["CO₂ Tolerance", "Calm", "Breath Control"],
        effects={"hr": "decrease", "hrv": "increase", "temperature": None},
        difficulty="intermediate",
        phases=[
            {"label": "Breathe In", "duration_sec": 3, "instruction": "Take a small, light inhale through the nose.", "animation": "expand"},
            {"label": "Hold", "duration_sec": 2, "instruction": "Pause briefly and stay relaxed.", "animation": "hold"},
            {"label": "Breathe Out", "duration_sec": 4, "instruction": "Exhale softly and reduce the urge to inhale again immediately.", "animation": "contract"},
        ],
        cycles=72,
    ),
    BreathworkProtocol(
        id="diaphragmatic-breathing",
        name="Diaphragmatic Breathing",
        category="Breathing Protocols",
        tagline="Train Full Belly Breathing",
        duration_mins=10,
        description="Diaphragmatic breathing teaches the practitioner to recruit the diaphragm efficiently, allowing the abdomen and lower ribs to expand instead of breathing shallowly into the upper chest. This improves ventilatory efficiency, helps regulate autonomic tone, and is one of the simplest tools for reducing anxiety and restoring a grounded breathing pattern.",
        origin="A foundational respiratory rehabilitation technique used in yoga, physical therapy, and stress-management training.",
        benefits=["Relaxation", "Breath Efficiency", "Posture"],
        effects={"hr": "decrease", "hrv": "increase", "temperature": None},
        difficulty="beginner",
        phases=[
            {"label": "Breathe In", "duration_sec": 4, "instruction": "Expand the belly and lower ribs on the inhale.", "animation": "expand"},
            {"label": "Hold", "duration_sec": 1, "instruction": "Pause without gripping the throat or chest.", "animation": "hold"},
            {"label": "Breathe Out", "duration_sec": 6, "instruction": "Let the belly soften as you exhale slowly.", "animation": "contract"},
        ],
        cycles=60,
    ),
    BreathworkProtocol(
        id="box-breathing",
        name="Box Breathing",
        category="Breathing Protocols",
        tagline="Balanced Focus Under Pressure",
        duration_mins=10,
        description="Box breathing equalizes inhalation, retention, exhalation, and the pause after exhalation to create a stable, repeatable rhythm. Because every side of the breath is matched, the technique is widely used for focus, emotional steadiness, and nervous-system regulation in stressful environments. It can feel both calming and sharpening at the same time.",
        origin="A structured tactical breathing drill used in pranayama and modern performance training alike.",
        benefits=["Focus", "Stress Relief", "Control"],
        effects={"hr": "decrease", "hrv": "increase", "temperature": None},
        difficulty="beginner",
        phases=[
            {"label": "Breathe In", "duration_sec": 4, "instruction": "Inhale evenly for four counts.", "animation": "expand"},
            {"label": "Hold", "duration_sec": 4, "instruction": "Hold steadily for four counts.", "animation": "hold"},
            {"label": "Breathe Out", "duration_sec": 4, "instruction": "Exhale evenly for four counts.", "animation": "contract"},
            {"label": "Hold", "duration_sec": 4, "instruction": "Pause empty for four counts.", "animation": "hold"},
        ],
        cycles=38,
    ),
    BreathworkProtocol(
        id="coherent-breathing",
        name="Coherent Breathing",
        category="Breathing Protocols",
        tagline="Sync Breath And Heart Rhythm",
        duration_mins=15,
        description="Coherent breathing is typically practiced at around five breaths per minute, most commonly with equal or near-equal inhale and exhale durations. This rhythm has been associated with improved heart-rate variability, stronger vagal tone, and better emotional balance. The practice is smooth, relaxed, and especially useful for stress recovery.",
        origin="Modern HRV and resonance-frequency training informed by slower yogic breathing patterns.",
        benefits=["HRV", "Calm", "Resilience"],
        effects={"hr": "decrease", "hrv": "increase", "temperature": None},
        difficulty="beginner",
        phases=[
            {"label": "Breathe In", "duration_sec": 5, "instruction": "Inhale gently for five seconds.", "animation": "expand"},
            {"label": "Hold", "duration_sec": 0, "instruction": "", "animation": "hold"},
            {"label": "Breathe Out", "duration_sec": 5, "instruction": "Exhale smoothly for five seconds.", "animation": "contract"},
        ],
        cycles=90,
    ),
    BreathworkProtocol(
        id="deep-breathing",
        name="Deep Breathing",
        category="Breathing Protocols",
        tagline="Simple Full-Body Reset",
        duration_mins=8,
        description="Deep breathing uses a fuller inhale and complete exhale to improve oxygen exchange, reduce muscle tension, and interrupt shallow stress breathing. It is one of the most accessible techniques for anyone starting breathwork, and it often creates a quick sense of ease and clarity when practiced without strain.",
        origin="A fundamental breath regulation practice found across yoga, meditation, and clinical relaxation training.",
        benefits=["Relaxation", "Energy Balance", "Ease"],
        effects={"hr": "decrease", "hrv": "increase", "temperature": None},
        difficulty="beginner",
        phases=[
            {"label": "Breathe In", "duration_sec": 4, "instruction": "Fill the lungs fully but comfortably.", "animation": "expand"},
            {"label": "Hold", "duration_sec": 2, "instruction": "Pause softly at the top.", "animation": "hold"},
            {"label": "Breathe Out", "duration_sec": 6, "instruction": "Exhale slowly until the lungs feel empty.", "animation": "contract"},
        ],
        cycles=40,
    ),
    BreathworkProtocol(
        id="alternate-nostril-breathing",
        name="Alternate Nostril Breathing",
        category="Breathing Protocols",
        tagline="Balance Left And Right Channels",
        duration_mins=12,
        description="Alternate nostril breathing coordinates nasal airflow, timing, and gentle breath retention to promote mental clarity and autonomic balance. Practitioners often report feeling centered and mentally quieter after only a few rounds. In yogic traditions, it is associated with harmonizing opposing energetic pathways and preparing the mind for meditation.",
        origin="Known as Nadi Shodhana in classical pranayama traditions.",
        benefits=["Balance", "Focus", "Calm"],
        effects={"hr": "decrease", "hrv": "increase", "temperature": None},
        difficulty="intermediate",
        phases=[
            {"label": "Breathe In", "duration_sec": 4, "instruction": "Inhale through one nostril with the other gently closed.", "animation": "expand"},
            {"label": "Hold", "duration_sec": 4, "instruction": "Pause while switching nostrils softly.", "animation": "hold"},
            {"label": "Breathe Out", "duration_sec": 4, "instruction": "Exhale through the opposite nostril.", "animation": "contract"},
            {"label": "Breathe In", "duration_sec": 4, "instruction": "Inhale through the new side to complete the round.", "animation": "expand"},
            {"label": "Hold", "duration_sec": 4, "instruction": "Switch nostrils with ease.", "animation": "hold"},
            {"label": "Breathe Out", "duration_sec": 4, "instruction": "Exhale back through the first side.", "animation": "contract"},
         ],
        cycles=18,
     ),
     BreathworkProtocol(
         id="kapalabhati",
         name="Kapalabhati",
         category="Breathing Protocols",
         tagline="Brighten Energy And Clear Sluggishness",
         duration_mins=6,
         description="Kapalabhati is a cleansing pranayama built around quick, forceful exhalations driven by the lower abdomen with passive inhales in between. It tends to feel energizing and stimulating, making it better suited to daytime practice rather than bedtime. Physiologically it can heighten alertness, raise ventilation, and produce a warming effect.",
         origin="A classical kriya and pranayama practice from hatha yoga traditions.",
         benefits=["Energy", "Heat", "Mental Clarity"],
         effects={"hr": "increase", "hrv": "decrease", "temperature": "increase"},
         difficulty="intermediate",
         phases=[
            {"label": "Breathe In", "duration_sec": 1, "instruction": "Allow a light passive inhale.", "animation": "expand"},
            {"label": "Breathe Out", "duration_sec": 1, "instruction": "Drive a quick, sharp exhale from the belly.", "animation": "contract"},
         ],
        cycles=180,
     ),
     BreathworkProtocol(
         id="buteyko-breathing",
         name="Buteyko Breathing",
         category="Breathing Protocols",
         tagline="Restore Quiet Nasal Breathing",
         duration_mins=10,
         description="Buteyko Breathing trains the body to breathe more quietly through the nose, reduce upper-chest effort, and improve tolerance to a mild sense of air hunger. It is often used to shift chronic over-breathing habits toward a calmer baseline. Practiced consistently, it may support nasal breathing mechanics and improved respiratory efficiency.",
         origin="Rooted in the Buteyko respiratory method developed for breath retraining.",
         benefits=["Nasal Breathing", "Calm", "Control"],
         effects={"hr": "decrease", "hrv": "increase", "temperature": None},
         difficulty="beginner",
         phases=[
             {"label": "Breathe In", "duration_sec": 3, "instruction": "Inhale lightly through the nose.", "animation": "expand"},
             {"label": "Hold", "duration_sec": 1, "instruction": "Pause gently and stay relaxed.", "animation": "hold"},
             {"label": "Breathe Out", "duration_sec": 4, "instruction": "Exhale silently and keep the breath light.", "animation": "contract"},
         ],
         cycles=75,
     ),
     BreathworkProtocol(
         id="holotropic-breathwork",
         name="Holotropic Breathwork",
         category="Breathing Protocols",
         tagline="Intense Exploratory Rhythmic Breathing",
         duration_mins=20,
         description="Holotropic Breathwork uses sustained, accelerated breathing patterns to create an intense altered-state experience that many practitioners describe as emotionally cathartic or visionary. The technique is not casual relaxation breathing; it is stimulating and can significantly change arousal, body sensations, and perceived energy. It is best approached carefully and traditionally with guidance.",
         origin="Developed by Stanislav and Christina Grof as a modern breath-based transpersonal practice.",
         benefits=["Catharsis", "Energy", "Exploration"],
         effects={"hr": "increase", "hrv": "decrease", "temperature": "increase"},
         difficulty="advanced",
         phases=[
            {"label": "Breathe In", "duration_sec": 2, "instruction": "Take a deep active inhale without pause between breaths.", "animation": "expand"},
            {"label": "Breathe Out", "duration_sec": 2, "instruction": "Exhale actively and continue the connected rhythm.", "animation": "contract"},
         ],
         cycles=300,
     ),
     BreathworkProtocol(
         id="tummo-breathing",
         name="Tummo Breathing",
         category="Breathing Protocols",
         tagline="Generate Inner Heat",
         duration_mins=12,
         description="Tummo breathwork pairs powerful breathing with retention and internal focus to create a strong warming effect in the body. It is associated with heightened alertness, intense concentration, and a sense of internal heat building over repeated rounds. The practice is demanding and generally better suited to experienced practitioners.",
         origin="A traditional Tibetan inner-heat practice adapted into modern breath training formats.",
         benefits=["Heat", "Focus", "Energy"],
         effects={"hr": "increase", "hrv": "steady", "temperature": "increase"},
         difficulty="advanced",
         phases=[
             {"label": "Breathe In", "duration_sec": 4, "instruction": "Inhale powerfully into the belly and chest.", "animation": "expand"},
             {"label": "Hold", "duration_sec": 8, "instruction": "Retain the breath with upright posture and internal focus.", "animation": "hold"},
             {"label": "Breathe Out", "duration_sec": 4, "instruction": "Exhale steadily while keeping the spine tall.", "animation": "contract"},
         ],
         cycles=45,
     ),
     BreathworkProtocol(
         id="ujjayi",
         name="Ujjayi",
         category="Breathing Protocols",
         tagline="Increase Concentration",
         duration_mins=10,
         description="Ujjayi breath is performed through the nose with a gentle constriction at the back of the throat, creating a soft oceanic or hissing sound. The audible texture helps anchor attention, lengthen the breath, and maintain an even pace during movement or meditation. Physiologically it can improve concentration, slow breathing, and support a more stable autonomic state.",
         origin="A classical yogic pranayama often practiced in vinyasa and meditative traditions.",
         benefits=["Concentration", "Stress Relief", "HRV"],
         effects={"hr": "decrease", "hrv": "increase", "temperature": None},
         difficulty="beginner",
         phases=[
             {"label": "Breathe In", "duration_sec": 4, "instruction": "Slowly through nose, slightly constrict the throat to make a hissing sound", "animation": "expand"},
             {"label": "Hold", "duration_sec": 0, "instruction": "", "animation": "hold"},
             {"label": "Breathe Out", "duration_sec": 6, "instruction": "Slowly through nose, maintaining hissing sound", "animation": "contract"},
         ],
         cycles=60,
     ),
     BreathworkProtocol(
         id="bhastrika",
         name="Bhastrika",
         category="Breathing Protocols",
         tagline="Bellows Breath For Vitality",
         duration_mins=6,
         description="Bhastrika, sometimes called bellows breath, uses forceful inhalations and exhalations of equal power to rapidly energize the system. The repeated pumping action can build heat, sharpen alertness, and increase respiratory drive. Because it is stimulating, it is best used intentionally and avoided when deep calm is the primary goal.",
         origin="A classical hatha yoga pranayama named for the motion of a blacksmith's bellows.",
         benefits=["Energy", "Heat", "Alertness"],
         effects={"hr": "increase", "hrv": "decrease", "temperature": "increase"},
         difficulty="intermediate",
         phases=[
             {"label": "Breathe In", "duration_sec": 1, "instruction": "Take a forceful inhale through the nose.", "animation": "expand"},
             {"label": "Breathe Out", "duration_sec": 1, "instruction": "Drive the exhale out with equal power.", "animation": "contract"},
         ],
         cycles=180,
     ),
     BreathworkProtocol(
         id="qi-gong-breathing",
         name="Qi Gong Breathing",
         category="Breathing Protocols",
         tagline="Smooth Breath For Energetic Balance",
         duration_mins=12,
         description="Qi Gong breathing favors a calm, continuous inhale and exhale coordinated with posture and internal awareness. The rhythm is usually relaxed and unforced, helping the practitioner settle attention while cultivating a sense of grounded energy. It is commonly used to restore calm and improve mind-body integration.",
         origin="A foundational breathing principle within traditional Chinese Qi Gong practices.",
         benefits=["Balance", "Calm", "Presence"],
         effects={"hr": "decrease", "hrv": "increase", "temperature": None},
         difficulty="beginner",
         phases=[
             {"label": "Breathe In", "duration_sec": 5, "instruction": "Inhale slowly through the nose and feel the lower abdomen expand.", "animation": "expand"},
             {"label": "Hold", "duration_sec": 1, "instruction": "Rest at the top without tension.", "animation": "hold"},
             {"label": "Breathe Out", "duration_sec": 5, "instruction": "Exhale smoothly and let the shoulders soften.", "animation": "contract"},
         ],
         cycles=65,
     ),
     BreathworkProtocol(
         id="soma-breathwork",
         name="Soma Breathwork",
         category="Breathing Protocols",
         tagline="Rhythmic Activation And Recovery",
         duration_mins=14,
         description="Soma Breathwork blends rhythmic breathing, timed breath retentions, and often music-led pacing to influence arousal and focus. It usually begins with energizing rhythmic breathing and transitions into deeper holds that can feel expansive or meditative. The method is intentionally immersive and can feel both activating and centering.",
         origin="A modern method influenced by pranayama, rhythm, and guided transformational breath practices.",
         benefits=["Focus", "Energy", "Mood"],
         effects={"hr": "increase", "hrv": "steady", "temperature": "increase"},
         difficulty="intermediate",
         phases=[
             {"label": "Breathe In", "duration_sec": 3, "instruction": "Inhale rhythmically and fully.", "animation": "expand"},
             {"label": "Breathe Out", "duration_sec": 3, "instruction": "Exhale in the same steady rhythm.", "animation": "contract"},
             {"label": "Hold", "duration_sec": 12, "instruction": "After the rhythm round, hold calmly and observe.", "animation": "hold"},
         ],
         cycles=28,
     ),
     BreathworkProtocol(
         id="wim-hof-method",
         name="Wim Hof Method",
         category="Breathing Protocols",
         tagline="Power Breaths, Hold, Recover",
         duration_mins=12,
         description="The Wim Hof Method cycles through repeated deep but relatively fast breaths followed by a long relaxed retention and a short recovery hold after a final inhale. This produces a distinct energetic shift and is often used to cultivate resilience, alertness, and cold-exposure readiness. It is potent and should be practiced seated or lying down in a safe environment.",
         origin="Popularized by Wim Hof from a broader mix of breathing, cold, and mindset practices.",
         benefits=["Resilience", "Energy", "Focus"],
         effects={"hr": "increase", "hrv": "steady", "temperature": "increase"},
         difficulty="intermediate",
         phases=[
             {"label": "Power Breaths", "duration_sec": 75, "instruction": "Take 30 deep connected breaths: inhale fully, exhale without forcing it all out.", "animation": "pulse"},
             {"label": "Hold", "duration_sec": 60, "instruction": "After the last exhale, hold empty as long as it remains comfortable.", "animation": "hold"},
             {"label": "Recovery Inhale", "duration_sec": 15, "instruction": "Take one deep inhale and hold briefly to recover.", "animation": "expand"},
         ],
         cycles=4,
     ),
     BreathworkProtocol(
         id="shamanic-breathing",
         name="Shamanic Breathing",
         category="Breathing Protocols",
         tagline="Rhythmic Breath For Trance And Release",
         duration_mins=15,
         description="Shamanic breathing uses a strong, repetitive rhythm to build intensity and support trance-like focus, emotional release, or ceremonial introspection. It tends to be more activating than calming and can create pronounced shifts in body sensation and awareness. Because of its intensity, it is best approached with respect and in a grounded context.",
         origin="Inspired by rhythmic ceremonial breath patterns used in various indigenous and modern transformational settings.",
         benefits=["Release", "Energy", "Exploration"],
         effects={"hr": "increase", "hrv": "decrease", "temperature": "increase"},
         difficulty="advanced",
         phases=[
             {"label": "Breathe In", "duration_sec": 2, "instruction": "Inhale deeply and rhythmically.", "animation": "expand"},
             {"label": "Breathe Out", "duration_sec": 2, "instruction": "Exhale fully and keep the tempo steady.", "animation": "contract"},
         ],
         cycles=225,
     ),
 ]


@router.get("/protocols", response_model=list[BreathworkProtocol])
def list_breathwork_protocols() -> list[BreathworkProtocol]:
    return BREATHWORK_PROTOCOLS
